version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: container_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: container_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./_docker/db/import:/var/www/_docker/db/import
    environment:
      MYSQL_ROOT_PASSWORD: a4b7ea0c30f83f4
      MYSQL_USER: Profi
      MYSQL_PASSWORD: a4b7a4b7
      MYSQL_DATABASE: my.store.technology
    ports:
      - "8181:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: container_db
