version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    container_name: nginx_container
    depends_on:
      - php

  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www
    container_name: php_container
